### ISSUE TITLE
How to use it with Angular

### ISSUE THREAD

**Issue by alcidesfmelof** [motdotla/signature-pad#2]
HI, good work.

I wonder how to use this with Angular as we cant not use <script src="">

I tried to use like this "$.getScript("/Scripts/signatureCollector.js");" , but it renders just on the bottom of the page and not where I wish.

Thank you

**Comment by motdotla** [comment]
Hi @alcidesfmelof,

Thank you :)

I'm not sure about Angular. I would try in the angular chat room. They might be able to help.
